
package com.europlayas.amadeus.bindings;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-11-08T12:42:57.121+01:00
 * Generated source version: 3.1.7
 */

@WebFault(name = "duplicateBookingFault", targetNamespace = "http://ws.amadeus.fr/air")
public class DuplicateBookingFault_Exception extends Exception {
    
    private com.europlayas.amadeus.bindings.DuplicateBookingFault duplicateBookingFault;

    public DuplicateBookingFault_Exception() {
        super();
    }
    
    public DuplicateBookingFault_Exception(String message) {
        super(message);
    }
    
    public DuplicateBookingFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public DuplicateBookingFault_Exception(String message, com.europlayas.amadeus.bindings.DuplicateBookingFault duplicateBookingFault) {
        super(message);
        this.duplicateBookingFault = duplicateBookingFault;
    }

    public DuplicateBookingFault_Exception(String message, com.europlayas.amadeus.bindings.DuplicateBookingFault duplicateBookingFault, Throwable cause) {
        super(message, cause);
        this.duplicateBookingFault = duplicateBookingFault;
    }

    public com.europlayas.amadeus.bindings.DuplicateBookingFault getFaultInfo() {
        return this.duplicateBookingFault;
    }
}
