
package com.europlayas.amadeus.bindings;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-11-07T15:50:32.435+01:00
 * Generated source version: 3.1.5
 */

@WebFault(name = "inconsistentLowFareSearchRequestFault", targetNamespace = "http://ws.amadeus.fr/air")
public class InconsistentLowFareSearchRequestFault_Exception extends Exception {
    
    private com.europlayas.amadeus.bindings.InconsistentLowFareSearchRequestFault inconsistentLowFareSearchRequestFault;

    public InconsistentLowFareSearchRequestFault_Exception() {
        super();
    }
    
    public InconsistentLowFareSearchRequestFault_Exception(String message) {
        super(message);
    }
    
    public InconsistentLowFareSearchRequestFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public InconsistentLowFareSearchRequestFault_Exception(String message, com.europlayas.amadeus.bindings.InconsistentLowFareSearchRequestFault inconsistentLowFareSearchRequestFault) {
        super(message);
        this.inconsistentLowFareSearchRequestFault = inconsistentLowFareSearchRequestFault;
    }

    public InconsistentLowFareSearchRequestFault_Exception(String message, com.europlayas.amadeus.bindings.InconsistentLowFareSearchRequestFault inconsistentLowFareSearchRequestFault, Throwable cause) {
        super(message, cause);
        this.inconsistentLowFareSearchRequestFault = inconsistentLowFareSearchRequestFault;
    }

    public com.europlayas.amadeus.bindings.InconsistentLowFareSearchRequestFault getFaultInfo() {
        return this.inconsistentLowFareSearchRequestFault;
    }
}
