
package com.europlayas.amadeus.bindings;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-11-07T15:50:32.424+01:00
 * Generated source version: 3.1.5
 */

@WebFault(name = "inconsistentAvailabilitySearchRequestFault", targetNamespace = "http://ws.amadeus.fr/air")
public class InconsistentAvailabilitySearchRequestFault_Exception extends Exception {
    
    private com.europlayas.amadeus.bindings.InconsistentAvailabilitySearchRequestFault inconsistentAvailabilitySearchRequestFault;

    public InconsistentAvailabilitySearchRequestFault_Exception() {
        super();
    }
    
    public InconsistentAvailabilitySearchRequestFault_Exception(String message) {
        super(message);
    }
    
    public InconsistentAvailabilitySearchRequestFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public InconsistentAvailabilitySearchRequestFault_Exception(String message, com.europlayas.amadeus.bindings.InconsistentAvailabilitySearchRequestFault inconsistentAvailabilitySearchRequestFault) {
        super(message);
        this.inconsistentAvailabilitySearchRequestFault = inconsistentAvailabilitySearchRequestFault;
    }

    public InconsistentAvailabilitySearchRequestFault_Exception(String message, com.europlayas.amadeus.bindings.InconsistentAvailabilitySearchRequestFault inconsistentAvailabilitySearchRequestFault, Throwable cause) {
        super(message, cause);
        this.inconsistentAvailabilitySearchRequestFault = inconsistentAvailabilitySearchRequestFault;
    }

    public com.europlayas.amadeus.bindings.InconsistentAvailabilitySearchRequestFault getFaultInfo() {
        return this.inconsistentAvailabilitySearchRequestFault;
    }
}
