
package com.europlayas.amadeus.bindings;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-11-08T12:42:57.174+01:00
 * Generated source version: 3.1.7
 */

@WebFault(name = "inconsistentBookRequestFault", targetNamespace = "http://ws.amadeus.fr/air")
public class InconsistentBookRequestFault_Exception extends Exception {
    
    private com.europlayas.amadeus.bindings.InconsistentBookRequestFault inconsistentBookRequestFault;

    public InconsistentBookRequestFault_Exception() {
        super();
    }
    
    public InconsistentBookRequestFault_Exception(String message) {
        super(message);
    }
    
    public InconsistentBookRequestFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public InconsistentBookRequestFault_Exception(String message, com.europlayas.amadeus.bindings.InconsistentBookRequestFault inconsistentBookRequestFault) {
        super(message);
        this.inconsistentBookRequestFault = inconsistentBookRequestFault;
    }

    public InconsistentBookRequestFault_Exception(String message, com.europlayas.amadeus.bindings.InconsistentBookRequestFault inconsistentBookRequestFault, Throwable cause) {
        super(message, cause);
        this.inconsistentBookRequestFault = inconsistentBookRequestFault;
    }

    public com.europlayas.amadeus.bindings.InconsistentBookRequestFault getFaultInfo() {
        return this.inconsistentBookRequestFault;
    }
}
