
package com.europlayas.amadeus.bindings;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-11-07T15:50:32.237+01:00
 * Generated source version: 3.1.5
 */

@WebFault(name = "passengerPriceDiscrepancyFault", targetNamespace = "http://ws.amadeus.fr/air")
public class PassengerPriceDiscrepancyFault_Exception extends Exception {
    
    private com.europlayas.amadeus.bindings.PassengerPriceDiscrepancyFault passengerPriceDiscrepancyFault;

    public PassengerPriceDiscrepancyFault_Exception() {
        super();
    }
    
    public PassengerPriceDiscrepancyFault_Exception(String message) {
        super(message);
    }
    
    public PassengerPriceDiscrepancyFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public PassengerPriceDiscrepancyFault_Exception(String message, com.europlayas.amadeus.bindings.PassengerPriceDiscrepancyFault passengerPriceDiscrepancyFault) {
        super(message);
        this.passengerPriceDiscrepancyFault = passengerPriceDiscrepancyFault;
    }

    public PassengerPriceDiscrepancyFault_Exception(String message, com.europlayas.amadeus.bindings.PassengerPriceDiscrepancyFault passengerPriceDiscrepancyFault, Throwable cause) {
        super(message, cause);
        this.passengerPriceDiscrepancyFault = passengerPriceDiscrepancyFault;
    }

    public com.europlayas.amadeus.bindings.PassengerPriceDiscrepancyFault getFaultInfo() {
        return this.passengerPriceDiscrepancyFault;
    }
}
