
package com.europlayas.amadeus.bindings;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-11-07T10:21:46.500+01:00
 * Generated source version: 3.1.5
 */

@WebFault(name = "priceDiscrepancyFault", targetNamespace = "http://ws.amadeus.fr/air")
public class PriceDiscrepancyFault_Exception extends Exception {
    
    private com.europlayas.amadeus.bindings.PriceDiscrepancyFault priceDiscrepancyFault;

    public PriceDiscrepancyFault_Exception() {
        super();
    }
    
    public PriceDiscrepancyFault_Exception(String message) {
        super(message);
    }
    
    public PriceDiscrepancyFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public PriceDiscrepancyFault_Exception(String message, com.europlayas.amadeus.bindings.PriceDiscrepancyFault priceDiscrepancyFault) {
        super(message);
        this.priceDiscrepancyFault = priceDiscrepancyFault;
    }

    public PriceDiscrepancyFault_Exception(String message, com.europlayas.amadeus.bindings.PriceDiscrepancyFault priceDiscrepancyFault, Throwable cause) {
        super(message, cause);
        this.priceDiscrepancyFault = priceDiscrepancyFault;
    }

    public com.europlayas.amadeus.bindings.PriceDiscrepancyFault getFaultInfo() {
        return this.priceDiscrepancyFault;
    }
}
