
package com.europlayas.amadeus.bindings;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-11-08T12:42:57.095+01:00
 * Generated source version: 3.1.7
 */

@WebFault(name = "ticketIssuanceFailureFault", targetNamespace = "http://ws.amadeus.fr/air")
public class TicketIssuanceFailureFault_Exception extends Exception {
    
    private com.europlayas.amadeus.bindings.TicketIssuanceFailureFault ticketIssuanceFailureFault;

    public TicketIssuanceFailureFault_Exception() {
        super();
    }
    
    public TicketIssuanceFailureFault_Exception(String message) {
        super(message);
    }
    
    public TicketIssuanceFailureFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public TicketIssuanceFailureFault_Exception(String message, com.europlayas.amadeus.bindings.TicketIssuanceFailureFault ticketIssuanceFailureFault) {
        super(message);
        this.ticketIssuanceFailureFault = ticketIssuanceFailureFault;
    }

    public TicketIssuanceFailureFault_Exception(String message, com.europlayas.amadeus.bindings.TicketIssuanceFailureFault ticketIssuanceFailureFault, Throwable cause) {
        super(message, cause);
        this.ticketIssuanceFailureFault = ticketIssuanceFailureFault;
    }

    public com.europlayas.amadeus.bindings.TicketIssuanceFailureFault getFaultInfo() {
        return this.ticketIssuanceFailureFault;
    }
}
