
package com.europlayas.amadeus.bindings;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-11-07T10:21:46.472+01:00
 * Generated source version: 3.1.5
 */

@WebFault(name = "unknownErrorFault", targetNamespace = "http://ws.amadeus.fr/air")
public class UnknownErrorFault_Exception extends Exception {
    
    private com.europlayas.amadeus.bindings.UnknownErrorFault unknownErrorFault;

    public UnknownErrorFault_Exception() {
        super();
    }
    
    public UnknownErrorFault_Exception(String message) {
        super(message);
    }
    
    public UnknownErrorFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public UnknownErrorFault_Exception(String message, com.europlayas.amadeus.bindings.UnknownErrorFault unknownErrorFault) {
        super(message);
        this.unknownErrorFault = unknownErrorFault;
    }

    public UnknownErrorFault_Exception(String message, com.europlayas.amadeus.bindings.UnknownErrorFault unknownErrorFault, Throwable cause) {
        super(message, cause);
        this.unknownErrorFault = unknownErrorFault;
    }

    public com.europlayas.amadeus.bindings.UnknownErrorFault getFaultInfo() {
        return this.unknownErrorFault;
    }
}
